create table ADDRESS
(
    ID                  INTEGER      NOT NULL,
    STREET_NAME         VARCHAR(256) NOT NULL,
    STREET_NUMBER       VARCHAR(10)  NOT NULL,
    POSTAL_CODE         INTEGER      NOT NULL,
    CITY                VARCHAR(256) NOT NULL,
    CONSTRAINT PK_ADDRESS primary key (ID)
);
CREATE SEQUENCE address_seq start with 1 increment by 1;

CREATE TABLE CUSTOMER
(
    ID            VARCHAR(256)  NOT NULL,
    FIRST_NAME    VARCHAR(100) NOT NULL,
    LAST_NAME     VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(100) NOT NULL,
    FK_ADDRESS_ID INTEGER NOT NULL,
    PHONE_NUMBER  VARCHAR(40)  NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID),
    CONSTRAINT FK_ADDRESS_ID_CUSTOMER FOREIGN KEY (FK_ADDRESS_ID) REFERENCES ADDRESS (ID)
);